[package]
name = "encrypter"
version = "0.1.0"
edition = "2021"

[dependencies]
magic-crypt = "3.1.12"
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "60e3c5b41e616fee239304d92128e117dd9be0a7" }
[lib]
crate-type = ["cdylib"]